server:
  port: 8082

spring:
  application:
    name: service-two

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/

service1:
  location: http://service-one/hello