server:
  port: 8765
  
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
     routes:
      - id: service-one-route
        uri: http://localhost:8091
        predicates:
        - Path=/hello/**

