server:
  port: 8081

spring:
  application:
    name: service-one
  config:
    import: optional:configserver:http://service-configuration:8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/